<?php $user=$view->getParam('user');?>
<div id="body">
<h2>Profile user</h2>
         <div id="userInfo">
              <div>
              <label> Name : </label>
              <span> <?php echo $user->login;?></span>
              </div>
              <div>
              <label> Email : </label>
              <span> <?php echo $user->email;?></span>
              </div>
          </div>  
<img alt="Photo" src="<?php echo !empty($user->photo)?$host_path.'/img/'.$user->photo:$host_path.'/img/img.png';?>"/>
</div>
        