<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo $_SERVER['SERVER_NAME'];?></title>
        <link href="<?php echo $host_path; ?>/css/layout.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $host_path.'/css/'.$controllerName.'.css'; ?>" rel="stylesheet" type="text/css"/>
    </head>
    <body>   
        <h1> Welcom to the <?php echo $_SERVER['SERVER_NAME'];?> </h1>