<?php 
    $userId = $controller->getUserId();
          
    $userRoleId = 0;
    if($userId) {
        $userModel      = Model_User::getById($userId);
        $userEmail      = $userModel->email;
        $userRoleId     = $userModel->role_id; 
    }

    $errorType = $controller->getParamByKey('error');
    $errorMessage = '';
    if(!empty($errorType)) {
        switch($errorType) {
            case System_Exception::ALREADY_EXIST:
                $errorMessage = 'Such account already exists!';
                break;
            case System_Exception::VALIDATE_ERROR:
                $errorMessage = 'Invalid enetered data!';
                break;
            case System_Exception::ERROR_CREATE_USER:
                $errorMessage = 'Can\'t create new user! Try again!';
                break;
            case System_Exception::INVALID_LOGIN:
                $errorMessage = 'Invalid user or password!';
                break;    
        }
    } 
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo $_SERVER['SERVER_NAME'];?></title>
        <link href="<?php echo $host_path; ?>/css/layout.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $host_path.'/css/'.$viewFolder.'/'.$actionName.'.css'; ?>" rel="stylesheet" type="text/css"/>
        <script src="<?php echo $host_path;?>/js/jquery.js" type="text/javascript"></script>
        <script src="<?php echo $host_path;?>/js/authorize.js" type="text/javascript"></script>
    </head>    
    <body>   
        <h1>  Добро пожаловать  на <?php echo $_SERVER['SERVER_NAME'];?> </h1>
        
        <div id="error"> <?php echo !empty($errorMessage) ? $errorMessage : ''; ?></div>
        
        <div class="userEnter">
        <div id="userEmail"> 
            <?php echo !empty($userId) ? 'Вы зашли как: ' : '';?>
            <a href="<?php echo !empty($userId) ? $host_path.'/user/profile/id/'.$userId : '';?>"><?php echo !empty($userEmail) ? $userEmail : ''; ?></a>
        </div>
        <div id="userId"><a id="logout" href="#"><?php echo !empty($userId) ? 'Exit' : ''?></a></div>
        </div>
        
        <div id="loginFormDiv" <?php if(!empty($userEmail)) { echo 'style="display: none;"'; } ?> >
           
            <form name="autorize" id="loginForm" method="POST" autocomplete="off">
                <input placeholder="Login" type="text" name="email" maxlength="20" /><br />
                <input placeholder="Password" type="password" name="password" maxlength="30" /><br />
                <input id="save_checkbox" type="checkbox" name="save" value="1" /><label for="save_checkbox">Save</label><br />
                <input type="submit" name="login" value="Enter" />
                <input type="submit" name="register" value="Register" />
            </form>
        </div>

        <?php //if( (!empty($userRoleId) && $userRoleId != Model_User::ROLE_ADMIN_ID) || empty($userRoleId) ) : ?>
            
            <div id="menu">
                <a href="<?php echo $host_path;?>/">Главная </a>  
                <a href="<?php echo $host_path;?>/product/index">Продукты </a>    
                <a href="<?php echo $host_path;?>/company/portfolio">Портфолио </a>   
                <a href="<?php echo $host_path;?>/company/about">О компании </a>   
                <a href="<?php echo $host_path;?>/company/contact">Контакты </a>   
                <?php //if ($userRoleId == Model_User::ROLE_ADMIN_ID) : ?> 
                    <a id="admin_href" href="/admin/index" style="<?php if($userRoleId != Model_User::ROLE_ADMIN_ID) { echo 'display: none;'; } ?>">Админка </a>  &nbsp&nbsp
                <?php //endif; ?>
            </div>
        
        <?php //else : ?>
        
<!--            <div id="admin_menu">
                <a href="<?php //echo $host_path;?>/customer/index">Клиенты </a> &nbsp&nbsp | &nbsp&nbsp
                <a href="<?php //echo $host_path;?>/product/index">Продукты </a>  &nbsp&nbsp | &nbsp&nbsp
                <a href="<?php// echo $host_path;?>/order/index">Заказы </a>  &nbsp&nbsp
            </div>-->
        
        <?php //endif; ?>
        <?php 
        //$scriptFile = 'js' . '/' . $viewFolder . '/' . $actionName. '.js';
        //if(file_exists($scriptFile)): ?>
            <!--<script src="<?php // echo '/' . $scriptFile; ?>"></script>-->
        <?php //endif; ?>
        <br />
        <hr />
<div id="forContent">
    <?php
        if(file_exists($viewFileName)) {
            include $viewFileName;
        }
    ?>
</div>
    </body>
    
</html>